MODULE_TOPDIR = /home/marisn/soft/grass-marisn

PGM = i.svm.optimize

ETCFILES = problems

include $(MODULE_TOPDIR)/include/Make/Script.make
include $(MODULE_TOPDIR)/include/Make/Python.make

default: script
